### ISSUE TITLE
Simpler way to use JS player

### ISSUE THREAD

**Issue by ku1ik** [eddiej/asciinema-rails#1]
Hey,

Recently the JS player got simpler API, so you don't need to manually construct HttpArraySource, Movie etc.

``` javascript
<div id="player-container"></div>
<script>
  asciinema.CreatePlayer(document.getElementById('player-container'), 80, 24, '/frames.json', 123.0, { speed: 2 })
</script>
```

Docs are here: https://github.com/asciinema/asciinema-player#usage

**Comment by eddiej** [comment]
Excellent, will update the docs - thanks for the heads up.
